version: "3"

services:  
  web:
    build: .
    image: runwaytest_web
    ports:
      - "80:80"
    depends_on:
      - mysql
  
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: myapp