version: "2.1"

services:  
  web:
    build: .
    image: runwaytest_web
    ports:
      - "80:80"
    depends_on:
      - "mysql"
  
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: myapp
    healthcheck:
      test: /usr/bin/mysql -h"172.18.0.2" --user=dev --password=123456 --execute "SHOW DATABASES;" || exit 1
      interval: 3s
      retries: 120
      timeout: 2s

  migrate:
    image: php:7.2
    build:
      context: .
      dockerfile: ./docker/cmd/Dockerfile
    command: ./migrate.sh
    depends_on:
      mysql:
        condition: service_healthy